config/routes.rb
Rails.application.routes.draw do
  resources :units
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: %i[ show edit update destroy ]

  # GET /units or /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1 or /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units or /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully created." }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully updated." }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_params
      params.require(:unit).permit(:name, :port, :active, :friendly)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scanner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/units/_form.html.erb
<%= form_with(model: unit) do |form| %>
  <% if unit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
        <% unit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :port, style: "display: block" %>
    <%= form.number_field :port %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.label :friendly, style: "display: block" %>
    <%= form.check_box :friendly %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/units/_unit.html.erb
<div id="<%= dom_id unit %>">
  <p>
    <strong>Name:</strong>
    <%= unit.name %>
  </p>

  <p>
    <strong>Port:</strong>
    <%= unit.port %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= unit.active %>
  </p>

  <p>
    <strong>Friendly:</strong>
    <%= unit.friendly %>
  </p>

</div>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Show this unit", @unit %> |
  <%= link_to "Back to units", units_path %>
</div>

app/views/units/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Units</h1>

<div id="units">
  <% @units.each do |unit| %>
    <%= render unit %>
    <p>
      <%= link_to "Show this unit", unit %>
    </p>
  <% end %>
</div>

<%= link_to "New unit", new_unit_path %>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Back to units", units_path %>
</div>

app/views/units/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @unit %>

<div>
  <%= link_to "Edit this unit", edit_unit_path(@unit) %> |
  <%= link_to "Back to units", units_path %>

  <%= button_to "Destroy this unit", @unit, method: :delete %>
</div>